import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { ArrowLeft, Shield, Globe, Mail } from 'lucide-react';

const PrivacyPolicy: React.FC = () => {
    const containerVariants = {
        hidden: { opacity: 0 },
        visible: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1,
                delayChildren: 0.2
            }
        }
    };

    const itemVariants = {
        hidden: { opacity: 0, y: 20 },
        visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] } }
    };

    return (
        <div className="min-h-screen bg-[#06120E] pb-24 selection:bg-[#A3E635] selection:text-[#06120E]">
            <section className="relative pt-40 pb-20 px-6 overflow-hidden">
                {/* Background Accent */}
                <div className="absolute top-0 right-0 w-full h-full opacity-5 pointer-events-none">
                    <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-96 h-96 bg-[#A3E635] blur-[150px] rounded-full" />
                </div>

                <div className="max-w-4xl mx-auto relative z-10">
                    <Link
                        to="/"
                        className="inline-flex items-center space-x-2 text-gray-500 hover:text-[#A3E635] transition-all duration-300 mb-16 text-xs uppercase tracking-widest font-bold group"
                    >
                        <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                        <span>Return Home</span>
                    </Link>

                    <motion.div
                        initial="hidden"
                        animate="visible"
                        variants={containerVariants}
                    >
                        <motion.div variants={itemVariants} className="mb-20">
                            <div className="flex items-center space-x-3 mb-6">
                                <Shield className="w-5 h-5 text-[#A3E635]" />
                                <h2 className="text-xs font-bold uppercase tracking-[0.4em] text-white">Trust & Compliance</h2>
                            </div>
                            <h1 className="text-5xl md:text-7xl font-serif text-white mb-8 leading-[1.1] tracking-tight">
                                Privacy <span className="italic text-gray-400">Policy</span>
                            </h1>
                            <p className="text-gray-500 text-sm uppercase tracking-widest font-medium">Last updated: January 2026</p>
                        </motion.div>

                        <motion.div variants={itemVariants} className="prose prose-invert max-w-none space-y-16">
                            <div className="space-y-6">
                                <p className="text-xl md:text-2xl text-gray-400 font-light leading-relaxed">
                                    Welcome to KANPY (“we”, “us”, “our”). This Privacy Policy governs your visit to <span className="text-white font-medium">www.kanpy.in</span> (the “Website”) and explains how we collect, use, disclose, and safeguard your information when you use our services.
                                </p>
                                <p className="text-gray-400 font-light leading-relaxed text-lg">
                                    By accessing or using our Website or submitting information through forms, you agree to the practices described in this Policy.
                                </p>
                            </div>

                            {/* Sections */}
                            {[
                                {
                                    title: "1. Definitions",
                                    content: [
                                        { label: "Service", text: "Service refers to the Website and all related features, content, and offerings provided by KANPY." },
                                        { label: "Personal Data", text: "Personal Data means data about a living individual that can be used to identify that person." },
                                        { label: "Usage Data", text: "Usage Data is automatically collected information generated by users’ use of the Website (e.g., pages visited, time on page, device type)." },
                                        { label: "Cookies", text: "Cookies are small text files stored on your device when you visit a website." },
                                        { label: "Data Controller", text: "For the purposes of this Policy, KANPY is the Data Controller of your information." }
                                    ]
                                },
                                {
                                    title: "2. Information We Collect",
                                    content: [
                                        { label: "Personal Data", text: "You may voluntarily provide: Full name, Email address, Phone number, Company name, and any other information you submit through forms." },
                                        { label: "Usage Data", text: "Automatically collected when you visit the Website, such as: IP address, Browser type & version, Pages visited, and Device information." },
                                        { label: "Cookies & Tracking", text: "We use cookies, beacons, tags, and scripts to collect information about your interaction with the Website." }
                                    ]
                                },
                                {
                                    title: "3. How We Use Your Data",
                                    list: [
                                        "Provide, operate, and maintain the Website",
                                        "Respond to your inquiries and requests",
                                        "Personalize and improve user experience",
                                        "Send newsletters and updates (only with consent)",
                                        "Analyze Website usage and performance",
                                        "Comply with legal obligations and prevent fraud"
                                    ]
                                },
                                {
                                    title: "4. Retention of Data",
                                    text: "We retain your Personal Data only as long as necessary to fulfill the purposes outlined in this Policy or as required by applicable laws."
                                },
                                {
                                    title: "5. Disclosure of Data",
                                    text: "We may disclose your information to comply with legal obligations, protect our rights, or with service providers who support our operations. We do not sell your Personal Data to third parties."
                                },
                                {
                                    title: "6. International Data Transfers",
                                    text: "Your information may be transferred to and maintained on servers located outside your country of residence. By using the Website, you consent to such transfers."
                                },
                                {
                                    title: "7. Security of Your Data",
                                    text: "We implement commercially reasonable technical and organizational measures to secure your Personal Data. However, no method of electronic transmission or storage is 100% secure."
                                },
                                {
                                    title: "8. Your Rights",
                                    text: "Depending on your location, you may have the right to access, correct, or delete your Personal Data, object to processing, or withdraw consent at any time."
                                },
                                {
                                    title: "9. Third-Party Services & Links",
                                    text: "Our Website may use third-party analytics and marketing tools. Their use of data is governed by their respective privacy policies. We are not responsible for the privacy practices of external sites."
                                },
                                {
                                    title: "10. Children’s Privacy",
                                    text: "The Website is not directed to individuals under the age of 18. We do not knowingly collect Personal Data from children under 18."
                                },
                                {
                                    title: "11. Changes to This Privacy Policy",
                                    text: "We may update this Privacy Policy at any time by posting the revised version on this page with a new “Last updated” date."
                                }
                            ].map((section, idx) => (
                                <motion.div key={idx} variants={itemVariants} className="space-y-8 border-t border-white/5 pt-12">
                                    <h3 className="text-2xl md:text-3xl font-serif text-white">{section.title}</h3>
                                    {section.text && (
                                        <p className="text-gray-400 font-light leading-relaxed text-lg">{section.text}</p>
                                    )}
                                    {section.content && (
                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                            {section.content.map((item, i) => (
                                                <div key={i} className="bg-white/5 p-6 rounded-2xl border border-white/5 hover:border-[#A3E635]/20 transition-colors">
                                                    <p className="text-[10px] uppercase tracking-widest text-[#A3E635] font-bold mb-2">{item.label}</p>
                                                    <p className="text-gray-300 text-sm font-light leading-relaxed">{item.text}</p>
                                                </div>
                                            ))}
                                        </div>
                                    )}
                                    {section.list && (
                                        <ul className="space-y-4">
                                            {section.list.map((item, i) => (
                                                <li key={i} className="flex items-center space-x-3 text-gray-400 font-light">
                                                    <div className="w-1.5 h-1.5 rounded-full bg-[#A3E635]" />
                                                    <span>{item}</span>
                                                </li>
                                            ))}
                                        </ul>
                                    )}
                                </motion.div>
                            ))}

                            {/* Contact Section */}
                            <motion.div variants={itemVariants} className="pt-24 text-center">
                                <div className="p-12 md:p-16 rounded-[48px] bg-gradient-to-br from-[#A3E635]/10 via-white/[0.02] to-transparent border border-white/5">
                                    <h3 className="text-3xl font-serif text-white mb-12">Contact Us</h3>
                                    <div className="flex flex-col md:flex-row items-center justify-center gap-8">
                                        <a href="mailto:info@kanpy.in" className="flex items-center space-x-3 text-white hover:text-[#A3E635] transition-colors group">
                                            <div className="p-4 rounded-full bg-white/5 group-hover:bg-[#A3E635]/20 transition-colors">
                                                <Mail className="w-5 h-5" />
                                            </div>
                                            <span className="font-bold tracking-widest uppercase text-xs">info@kanpy.in</span>
                                        </a>
                                        <a href="https://www.kanpy.in" className="flex items-center space-x-3 text-white hover:text-[#A3E635] transition-colors group">
                                            <div className="p-4 rounded-full bg-white/5 group-hover:bg-[#A3E635]/20 transition-colors">
                                                <Globe className="w-5 h-5" />
                                            </div>
                                            <span className="font-bold tracking-widest uppercase text-xs">www.kanpy.in</span>
                                        </a>
                                    </div>
                                </div>
                            </motion.div>
                        </motion.div>
                    </motion.div>
                </div>
            </section>
        </div>
    );
};

export default PrivacyPolicy;
